run mode *ARGS:
    @just build {{ mode }}
    @echo "Running..."
    @find build/{{ uppercamelcase(mode) }}/executable/ -type f -exec ./{} {{ ARGS }} \;

build mode:
    @just cmake {{ mode }}
    @echo "Building..."
    @cmake --build build/{{ uppercamelcase(mode) }}

cmake mode:
    @echo "Running cmake with CMAKE_BUILD_TYPE={{ uppercamelcase(mode) }}..."
    @cmake -B build/{{ uppercamelcase(mode) }} -S . -D CMAKE_BUILD_TYPE={{ uppercamelcase(mode) }}

clean:
    @rm -rf build
