[workspace]
authors = ["Alexandre Bry <alexandre.bry@ign.fr>"]
channels = ["conda-forge"]
name = "points_to_prints"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
entwine = ">=3.2.1,<4"
duckdb = ">=1.5.1,<2"

[feature.python.dependencies]
python = ">=3.14.0,<4"
gdal = ">=3.12.1,<4"
httpx = ">=0.28.1,<0.29"
pdal = ">=2.9.3,<3"
pyproj = ">=3.7.2,<4"
tqdm = ">=4.67.2,<5"
typer = ">=0.21.1,<1"
matplotlib = ">=3.10.8,<4"

[feature.python.tasks]
py = { cmd = "cd \"$INIT_CWD\" && python" }
py-run = { cmd = "cd \"$INIT_CWD\" && python \"$PIXI_PROJECT_ROOT\"/python/main.py" }

[feature.cpp.dependencies]
just = ">=1.46.0,<2"
gdal = ">=3.12.2,<4"
pdal = ">=2.9.3,<3"
cgal = ">=6.0.1,<7"
libarrow-all = ">=23.0.0,<24"
cmake = ">=4.2.3,<5"
doxygen = ">=1.13.2,<2"
eigen = ">=3.4.0,<4"

[feature.cpp.tasks]
cpp = { cmd = "cd \"$INIT_CWD\" && just" }
cpp-run = { cmd = "cd \"$INIT_CWD\" && just run release" }
cpp-run-only = { cmd = "cd \"$INIT_CWD\" && just run-only release" }
cpp-build = { cmd = "cd \"$INIT_CWD\" && just build release" }
cpp-run-debug = { cmd = "cd \"$INIT_CWD\" && just run debug" }

[environments]
# python = ["python"]
# cpp = ["cpp"]
default = ["cpp", "python"]

[pypi-dependencies]
fastquadtree = ">=2.1.1, <3"
